In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

In [9]:
pldf = pd.DataFrame.from_csv('combined-stats.csv', index_col=False)

C:\Users\Mike\Anaconda2\envs\py35\lib\site-packages\IPython\core\interactiveshell.py:2821: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [10]:
pldf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603493 entries, 0 to 603492
Data columns (total 44 columns):
game_id           603493 non-null object
data_set          603493 non-null object
date              603493 non-null object
a1                603493 non-null object
a2                603493 non-null object
a3                603493 non-null object
a4                603493 non-null object
a5                603493 non-null object
h1                603493 non-null object
h2                603493 non-null object
h3                603493 non-null object
h4                603493 non-null object
h5                603493 non-null object
period            603493 non-null int64
away_score        603493 non-null int64
home_score        603493 non-null int64
remaining_time    603493 non-null object
elapsed           603493 non-null object
play_length       603493 non-null object
play_id           603493 non-null int64
team              548521 non-null object
event_type        603493 non-null object
assist            60131 non-null object
away              2240 non-null object
home              2240 non-null object
block             14740 non-null object
entered           58525 non-null object
left              58525 non-null object
num               60620 non-null float64
opponent          52351 non-null object
outof             60620 non-null float64
player            550045 non-null object
points            283941 non-null float64
possession        2127 non-null object
reason            86236 non-null object
result            283941 non-null object
steal             20153 non-null object
type              603493 non-null object
shot_distance     223321 non-null object
original_x        223321 non-null object
original_y        223321 non-null object
converted_x       223321 non-null object
converted_y       223321 non-null object
description       587352 non-null object
dtypes: float64(3), int64(4), object(37)
memory usage: 202.6+ MB

In [11]:
pldf.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
0,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN
1,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose
2,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,made,NaN,Driving Layup,1,4,8,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST)
3,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,missed,NaN,Hook Shot,4,-11,36,23.9,85.4,MISS Love 4' Hook Shot
4,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1)

In [16]:
import time, datetime

def convertTime(t):
    x = time.strptime(t, '%H:%M:%S')
    return int(int(datetime.timedelta(hours=x.tm_hour,minutes=x.tm_min,seconds=x.tm_sec).total_seconds()))

In [17]:
pldf['remaining_time_sec'] = pldf['remaining_time'].apply(convertTime)

In [18]:
pldf.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description,remaining_time_sec
0,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN,720
1,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,720
2,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,made,NaN,Driving Layup,1,4,8,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),700
3,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,missed,NaN,Hook Shot,4,-11,36,23.9,85.4,MISS Love 4' Hook Shot,686
4,"=""0021600001""",2016-2017 Regular Season,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,...,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1),683

In [19]:
pldf['elapsed_sec'] = pldf['elapsed'].apply(convertTime)

In [21]:
try:
    pldf['play_length_sec'] = pldf['play_length'].apply(convertTime)
except:
    pass

In [24]:
pldf.play_length.replace(['00:-12:00', '00:-5:00'], ['00:00:00', '00:00:00'], inplace=True)

In [25]:
pldf['play_length_sec'] = pldf['play_length'].apply(convertTime)

In [56]:
pldf = pldf.rename(columns={'team_in_position':'team_in_possession'})

In [30]:
pldf[['num', 'outof']] = pldf[['num', 'outof']].apply(pd.to_numeric)

In [33]:
pldf['num'] = pldf['num'].fillna(0).astype(int)

In [34]:
pldf['outof'] = pldf['outof'].fillna(np.nan).astype(int)

In [36]:
pldf['points'] = pldf['points'].fillna(0).astype(int)

In [52]:
pldf.shot_distance.replace(['np.nan'], [np.nan], inplace=True)

In [54]:
pldf[['shot_distance']] = pldf[['shot_distance']].apply(pd.to_numeric, errors='ignore')

In [63]:
pldf.original_x.replace(['unknown'], [np.nan], inplace=True)
pldf.original_y.replace(['unknown'], [np.nan], inplace=True)
pldf.converted_x.replace(['unknown'], [np.nan], inplace=True)
pldf.converted_y.replace(['unknown'], [np.nan], inplace=True)

In [64]:
pldf[['original_x', 'original_y', 'converted_x', 'converted_y']] = pldf[['original_x', 'original_y', 'converted_x', 'converted_y']].apply(pd.to_numeric)

In [67]:
pldf.drop('data_set', axis=1,inplace=True)

In [68]:
pldf.drop('play_length', axis=1,inplace=True)
pldf.drop('elapsed', axis=1,inplace=True)
pldf.drop('remaining_time', axis=1,inplace=True)

In [71]:
pldf['date'] = pd.to_datetime(pldf['date'])

In [80]:
pldf.head()

,game_id,date,a1,a2,a3,a4,a5,h1,h2,h3,...,type,shot_distance,original_x,original_y,converted_x,converted_y,description,remaining_time_sec,elapsed_sec,play_length_sec
0,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,start of period,NaN,NaN,NaN,NaN,NaN,NaN,720,0,0
1,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,720,0,0
2,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,Driving Layup,1.0,4.0,8.0,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),700,20,20
3,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,Hook Shot,4.0,-11.0,36.0,23.9,85.4,MISS Love 4' Hook Shot,686,34,14
4,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1),683,37,3

In [76]:
pldf['game_id'] = pldf['game_id'].map(lambda x: x.lstrip('="').rstrip('"'))

In [79]:
pldf['game_id'] = pldf['game_id'].fillna(0).astype(int)

In [82]:
pldf.to_csv('play_by_play_cleaned.csv')

In [84]:
cleandf = pd.DataFrame.from_csv('play_by_play_cleaned.csv')

In [85]:
cleandf.head()

,game_id,date,a1,a2,a3,a4,a5,h1,h2,h3,...,type,shot_distance,original_x,original_y,converted_x,converted_y,description,remaining_time_sec,elapsed_sec,play_length_sec
0,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,start of period,NaN,NaN,NaN,NaN,NaN,NaN,720,0,0
1,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Thompson vs. Noah: Tip to Rose,720,0,0
2,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,Driving Layup,1.0,4.0,8.0,24.6,5.8,Rose 1' Driving Layup (2 PTS) (Noah 1 AST),700,20,20
3,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,Hook Shot,4.0,-11.0,36.0,23.9,85.4,MISS Love 4' Hook Shot,686,34,14
4,21600001,2016-10-25,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose,LeBron James,Kevin Love,Tristan Thompson,...,rebound defensive,NaN,NaN,NaN,NaN,NaN,Noah REBOUND (Off:0 Def:1),683,37,3

In [86]:
cleandf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 603493 entries, 0 to 603492
Data columns (total 43 columns):
game_id               603493 non-null int64
date                  603493 non-null object
a1                    603493 non-null object
a2                    603493 non-null object
a3                    603493 non-null object
a4                    603493 non-null object
a5                    603493 non-null object
h1                    603493 non-null object
h2                    603493 non-null object
h3                    603493 non-null object
h4                    603493 non-null object
h5                    603493 non-null object
period                603493 non-null int64
away_score            603493 non-null int64
home_score            603493 non-null int64
play_id               603493 non-null int64
team_in_possession    548521 non-null object
event_type            603493 non-null object
assist                60131 non-null object
away                  2240 non-null object
home                  2240 non-null object
block                 14740 non-null object
entered               58525 non-null object
left                  58525 non-null object
num                   603493 non-null int64
opponent              52351 non-null object
outof                 603493 non-null int64
player                550045 non-null object
points                603493 non-null int64
possession            2127 non-null object
reason                86236 non-null object
result                283941 non-null object
steal                 20153 non-null object
type                  603493 non-null object
shot_distance         223316 non-null float64
original_x            223052 non-null float64
original_y            223052 non-null float64
converted_x           223052 non-null float64
converted_y           223052 non-null float64
description           587352 non-null object
remaining_time_sec    603493 non-null int64
elapsed_sec           603493 non-null int64
play_length_sec       603493 non-null int64
dtypes: float64(5), int64(11), object(27)
memory usage: 202.6+ MB