In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

In [12]:
tbdf = pd.DataFrame.from_csv('../../Cleaned_NBA_Season_Data/box_Score_Team-Stats_csv.csv', index_col=False)

In [13]:
tbdf.head()

,DATASET,DATE,TEAMS,VENUE,1Q,2Q,3Q,4Q,OT1,OT2,...,POSS,PACE,OEFF,DEFF,REST DAYS,STARTING LINEUPS1,STARTING LINEUPS2,STARTING LINEUPS3,STARTING LINEUPS4,STARTING LINEUPS5
0,2016-2017 Regular Season,10/25/2016,New York,Road,18,27,19,24,NaN,NaN,...,100.4,100.4,87.7,116.6,3+,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose
1,2016-2017 Regular Season,10/25/2016,Cleveland,Home,28,20,34,35,NaN,NaN,...,100.4,100.4,116.6,87.7,3+,LeBron James,Kevin Love,Tristan Thompson,JR Smith,Kyrie Irving
2,2016-2017 Regular Season,10/25/2016,Utah,Road,26,20,37,21,NaN,NaN,...,92.5,92.5,112.4,122.1,3+,Joe Johnson,Boris Diaw,Rudy Gobert,Rodney Hood,George Hill
3,2016-2017 Regular Season,10/25/2016,Portland,Home,26,28,23,36,NaN,NaN,...,92.5,92.5,122.1,112.4,3+,Maurice Harkless,Al-Farouq Aminu,Mason Plumlee,CJ McCollum,Damian Lillard
4,2016-2017 Regular Season,10/25/2016,San Antonio,Road,31,33,33,32,NaN,NaN,...,98.8,98.8,130.6,101.2,3+,Kawhi Leonard,LaMarcus Aldridge,Pau Gasol,Kyle Anderson,Tony Parker

In [14]:
tbdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Data columns (total 40 columns):
DATASET              2460 non-null object
DATE                 2460 non-null object
TEAMS                2460 non-null object
VENUE                2460 non-null object
1Q                   2460 non-null int64
2Q                   2460 non-null int64
3Q                   2460 non-null int64
4Q                   2460 non-null int64
OT1                  140 non-null float64
OT2                  16 non-null float64
OT3                  2 non-null float64
OT4                  2 non-null float64
F                    2460 non-null int64
MIN                  2460 non-null int64
FG                   2460 non-null int64
FGA                  2460 non-null int64
3P                   2460 non-null int64
3PA                  2460 non-null int64
FT                   2460 non-null int64
FTA                  2460 non-null int64
OR                   2460 non-null int64
DR                   2460 non-null int64
TOT                  2460 non-null int64
A                    2460 non-null int64
PF                   2460 non-null int64
ST                   2460 non-null int64
TO                   2460 non-null int64
TO TO                2460 non-null int64
BL                   2460 non-null int64
PTS                  2460 non-null int64
POSS                 2460 non-null float64
PACE                 2460 non-null float64
OEFF                 2460 non-null float64
DEFF                 2460 non-null float64
REST DAYS            2460 non-null object
STARTING LINEUPS1    2460 non-null object
STARTING LINEUPS2    2460 non-null object
STARTING LINEUPS3    2460 non-null object
STARTING LINEUPS4    2460 non-null object
STARTING LINEUPS5    2460 non-null object
dtypes: float64(8), int64(22), object(10)
memory usage: 768.8+ KB

In [15]:
tbdf.drop('DATASET', axis=1, inplace=True)

In [16]:
tbdf['DATE'] = pd.to_datetime(tbdf['DATE'])

In [22]:
tbdf['OT1'].unique()

array([ nan,   6.,  15.,   8.,  11.,   9.,   3.,  12.,   5.,  17.,  14.,
        10.,   1.,  13.,  16.,   7.,  21.,  19.,  20.,   4.])

In [25]:
tbdf.head()

,DATE,TEAMS,VENUE,1Q,2Q,3Q,4Q,OT1,OT2,OT3,...,POSS,PACE,OEFF,DEFF,REST DAYS,STARTING LINEUPS1,STARTING LINEUPS2,STARTING LINEUPS3,STARTING LINEUPS4,STARTING LINEUPS5
0,2016-10-25,New York,Road,18,27,19,24,NaN,NaN,NaN,...,100.4,100.4,87.7,116.6,3+,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose
1,2016-10-25,Cleveland,Home,28,20,34,35,NaN,NaN,NaN,...,100.4,100.4,116.6,87.7,3+,LeBron James,Kevin Love,Tristan Thompson,JR Smith,Kyrie Irving
2,2016-10-25,Utah,Road,26,20,37,21,NaN,NaN,NaN,...,92.5,92.5,112.4,122.1,3+,Joe Johnson,Boris Diaw,Rudy Gobert,Rodney Hood,George Hill
3,2016-10-25,Portland,Home,26,28,23,36,NaN,NaN,NaN,...,92.5,92.5,122.1,112.4,3+,Maurice Harkless,Al-Farouq Aminu,Mason Plumlee,CJ McCollum,Damian Lillard
4,2016-10-25,San Antonio,Road,31,33,33,32,NaN,NaN,NaN,...,98.8,98.8,130.6,101.2,3+,Kawhi Leonard,LaMarcus Aldridge,Pau Gasol,Kyle Anderson,Tony Parker

In [26]:
tbdf.to_csv('team_box_score_cleaned.csv')

In [27]:
clean_team_box_score_df = pd.DataFrame.from_csv('../../Cleaned_NBA_Season_Data/team_box_score_cleaned.csv')

In [28]:
clean_team_box_score_df.head()

,DATE,TEAMS,VENUE,1Q,2Q,3Q,4Q,OT1,OT2,OT3,...,POSS,PACE,OEFF,DEFF,REST DAYS,STARTING LINEUPS1,STARTING LINEUPS2,STARTING LINEUPS3,STARTING LINEUPS4,STARTING LINEUPS5
0,2016-10-25,New York,Road,18,27,19,24,NaN,NaN,NaN,...,100.4,100.4,87.7,116.6,3+,Carmelo Anthony,Kristaps Porzingis,Joakim Noah,Courtney Lee,Derrick Rose
1,2016-10-25,Cleveland,Home,28,20,34,35,NaN,NaN,NaN,...,100.4,100.4,116.6,87.7,3+,LeBron James,Kevin Love,Tristan Thompson,JR Smith,Kyrie Irving
2,2016-10-25,Utah,Road,26,20,37,21,NaN,NaN,NaN,...,92.5,92.5,112.4,122.1,3+,Joe Johnson,Boris Diaw,Rudy Gobert,Rodney Hood,George Hill
3,2016-10-25,Portland,Home,26,28,23,36,NaN,NaN,NaN,...,92.5,92.5,122.1,112.4,3+,Maurice Harkless,Al-Farouq Aminu,Mason Plumlee,CJ McCollum,Damian Lillard
4,2016-10-25,San Antonio,Road,31,33,33,32,NaN,NaN,NaN,...,98.8,98.8,130.6,101.2,3+,Kawhi Leonard,LaMarcus Aldridge,Pau Gasol,Kyle Anderson,Tony Parker